// File: dff.v
// Generated by MyHDL 0.11
// Date: Fri May 26 12:33:48 2023


`timescale 1ns/10ps

module dff (
    q,
    d,
    clk
);


output q;
reg q;
input d;
input clk;




always @(posedge clk) begin: DFF_LOGIC
    q <= d;
end

endmodule
